# Generated by Django 4.0.5 on 2024-10-02 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_alter_vehiculo_categoria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': (('visualizar_catalogo', 'Puede visualizar el catálogo de vehículos'),)},
        ),
    ]
